/** Shared sample catalog used by mock JSON seed and MongoDB seed. */
const SAMPLE_PRODUCTS = [
  {
    name: '24K Gold Sovereign Coin',
    description: 'Pure 24K gold investment grade sovereign coin.',
    price: 499,
    category: 'Gold',
    images: ['https://images.unsplash.com/photo-1610375461246-83df859d849d?auto=format&fit=crop&w=800&q=80'],
    stock: 25,
    brand: 'Royal Mint',
    ratingsAverage: 4.9,
    ratingsQuantity: 12,
  },
  {
    name: 'Diamond Encrusted Necklace',
    description: 'Elegant jewelry piece with real diamonds and platinum.',
    price: 1299,
    category: 'Jewelry',
    images: ['https://images.unsplash.com/photo-1599643478524-fb66f70a00d8?auto=format&fit=crop&w=800&q=80'],
    stock: 5,
    brand: 'Lusso',
    ratingsAverage: 5.0,
    ratingsQuantity: 8,
  },
  {
    name: 'Classic Chronograph Watch',
    description: 'Swiss made classic chronograph with leather strap.',
    price: 899,
    category: 'Watches',
    images: ['https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=800&q=80'],
    stock: 15,
    brand: 'Tempo',
    ratingsAverage: 4.7,
    ratingsQuantity: 45,
  },
  {
    name: 'Vintage Heritage Collection',
    description: 'A curated collection of vintage pieces.',
    price: 3499,
    category: 'Collections',
    images: ['https://images.unsplash.com/photo-1574344955745-776f30d075eb?auto=format&fit=crop&w=800&q=80'],
    stock: 2,
    brand: 'Aura',
    ratingsAverage: 4.8,
    ratingsQuantity: 3,
  },
  {
    name: 'Rose Gold Bracelet',
    description: '18k Rose Gold with intricate design patterns.',
    price: 349,
    category: 'Jewelry',
    images: ['https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=800&q=80'],
    stock: 20,
    brand: 'Aura',
    ratingsAverage: 4.6,
    ratingsQuantity: 28,
  },
  {
    name: 'Gold Ingot 1oz',
    description: 'Standard 1oz fine gold ingot.',
    price: 1850,
    category: 'Gold',
    images: ['https://images.unsplash.com/photo-1587813589415-389178cc0208?auto=format&fit=crop&w=800&q=80'],
    stock: 50,
    brand: 'Global Mint',
    ratingsAverage: 4.9,
    ratingsQuantity: 150,
  }
];

const ADMIN_ACCOUNT = {
  name: 'System Admin',
  email: 'admin@goldmarket.com',
  password: 'admin12345',
  role: 'admin',
  isVerified: true,
  provider: 'email',
};

module.exports = { SAMPLE_PRODUCTS, ADMIN_ACCOUNT };
